CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO tasks (title, done)
SELECT title, done
FROM (
    VALUES
        ('Learn FastAPI', FALSE),
        ('Build CRUD API', FALSE),
        ('Push project to GitHub', TRUE)
) AS example_tasks(title, done)
WHERE NOT EXISTS (
    SELECT 1 FROM tasks
);